spring:
  application:
    # 给 当前服务起一个名字
    name: smart-user-service
  # 【关键】默认激活的环境。
  # 本地开发默认走 dev，部署到服务器时通过命令参数覆盖为 prod
  profiles:
    active: dev

# 公共日志格式 (所有环境通用)
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"

# Knife4j 配置
knife4j:
  enable: true
  openapi:
    title: SpringBoot3 用户服务 API 文档
    description: 智能系统用户服务 API 文档
    email: xpcmty@icloud.com
    concat: mty
    version: 1.0.0


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开发期打印 SQL