<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <!-- 【关键】声明父工程，继承版本和管理配置 -->

    <!-- 继承父工程 -->
    <parent>
        <groupId>com.smart.community</groupId>
        <artifactId>smart-community</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath> <!-- 指向父工程 pom.xml 的路径 -->
    </parent>

    <!-- 子模块信息 -->
    <artifactId>smart-community-common</artifactId>
    <name>smart-community-common</name>
    <description>智能社区公共模块</description>


    <dependencies>
        <!-- 1. Lombok (继承父工程版本) -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <!-- optional 标签表示可选依赖，不打包 -->
            <optional>true</optional>
        </dependency>
        <!-- 2. Hutool (继承父工程版本) -->
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
        </dependency>
        <!-- 3. Web 依赖 (provided 范围，只编译不打包) -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <!-- provided 范围，只编译不打包 -->
            <scope>provided</scope>
        </dependency>
        <!-- JWT 认证（0.12.3 适配 SpringBoot3）-->
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-api</artifactId>
        </dependency>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-impl</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt-jackson</artifactId>
            <scope>runtime</scope>
        </dependency>
        <!--            swagger-->
        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
        </dependency>
        <!-- Spring Security Crypto (BCrypt 加密，Spring Boot 自动管理版本) -->
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-crypto</artifactId>
        </dependency>
    </dependencies>

    <!-- 注意：子模块不需要 build 和 dependencyManagement 标签，全部由父工程接管 -->
</project>