server:
  port: 18001

spring:
  config:
    import: # 导入Nacos配置,就可以不再在application-dev.yml中配置Nacos的地址、用户名、密码、命名空间、分组、文件扩展名
      - optional:nacos:smart-user-dev.yaml
# 日志
logging:
  level:
    com.alibaba.cloud.nacos: DEBUG

knife4j:
  setting:
    language: zh_cn