server:
  port: 18080 # 生产环境通常用 8080 或 80

spring:
  cloud:
    nacos:
      discovery:
        # 将来这里填生产环境的 Nacos IP
        server-addr: 192.168.69.223:8848
        username: nacos
        password: nacos # 生产环境建议使用更复杂的密码或从环境变量读取

      config:
        server-addr: 192.168.69.223:8848
        file-extension: yaml
        namespace: prod # 将来可能是独立的命名空间

# 生产环境：日志精简，避免泄露敏感信息，提升性能
logging:
  level:
    root: WARN       # 根日志级别调高
    com.smart.user: INFO  # 自己的包只打印 INFO
    com.alibaba.cloud.nacos: WARN # Nacos 报错才打印